name: 'Setup Python Environment'
description: 'Setup Python and install project dependencies.'
author: 'David Zhang'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  dependencies:
    description: 'Dependency group to install (e.g., "dev", "docs", "build")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python {% raw %}${{ inputs.python-version }}{% endraw %}
      uses: actions/setup-python@v5
      with:
        python-version: {% raw %}${{ inputs.python-version }}{% endraw %}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[{% raw %}${{ inputs.dependencies }}{% endraw %}]"
